global:
  scrape_interval: 2m

scrape_configs:
  - job_name: 'vmalert'
    static_configs:
      - targets: ['vmalert:8880']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'victorialogs'
    static_configs:
      - targets: ['victorialogs:9428']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
